ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "roomNumber" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "preferredContactAt" TIMESTAMP(3);
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "preferredVisitAt" TIMESTAMP(3);
